version: '3.9'
services:
  glpi_app:
    image: sdbrasil/glpi:10.0.15
    container_name: glpi-10
    volumes:
      - ./glpi_config:/etc/glpi
      - ./glpi_documents:/var/lib/glpi/files/data-documents
      - ./glpi_plugins:/usr/share/glpi/plugins
      - ./glpi_marketplace:/usr/share/glpi/marketplace
      - ./glpi_files_plugins:/var/lib/glpi/files/_plugins
      - ./glpi_backup:/backup
    networks:
      - glpi
    depends_on:
      - db-glpi-10
    ports:
      - 80:80

  db-glpi-10:   #não mudar - porque é o nome que o script do glpi espera para o banco de dados
    image: percona/percona-server:8.0
    container_name: db-glpi
    networks:
      - glpi
    volumes:
      - ./glpi_db_log:/var/log/mysql
      - ./glpi_db_lib:/var/lib/mysql
      - ./glpi_db_backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=ADM@MySQL_GLP1
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=GLP1_MySQL@10
      - TZ=America/Manaus 
  
  glpi-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-glpi-10
    networks:
      - glpi
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-glpi-10
      - PMA_PORT=3306
      # limitar o tamano do arquivo de importacao
      - PHP_UPLOAD_MAX_FILESIZE=1000M
      - PHP_MAX_INPUT_VARS=100000
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_MEMORY_LIMIT=512M
      - TZ=America/Manaus
    ports:
      - 8080:80
    
    depends_on:
      - db-glpi-10
    restart: always  # reinicia o phpMyAdmin até conseguir acessar o banco

volumes:
  glpi_config:
  glpi_documents:
  glpi_plugins:
  glpi_marketplace:
  glpi_files_plugins:
  glpi_backup:
  glpi_db_log:
  glpi_db_lib:
  glpi_db_backup:

#network create --subnet=172.16.0.0/16 glpi
networks:
  glpi:
    external: true   
